### ISSUE TITLE
Перейти на LTS версию Unity

### ISSUE THREAD

**Issue by CompletePast** [myjname/The-Rough-World#24]
Потому что перекачивать движок каждую неделю это извращение. Всё равно никто функции новых версий не использует.

**Comment by myjname** [comment]
Перейду, как только у Unity появиться новая LTS, ибо переходить на старую версию я не собираюсь

**Comment by CompletePast** [comment]
Будто ты используешь функции новой версии. От того что ты перейдешь на старую, ты не потеряешь.

**Comment by CompletePast** [comment]
Перейти на LTS версию сейчас не представляется возможным. Ждём выхода LTS 2019.
